sudo: required
dist: trusty
language: cpp

compiler: gcc

before_install:
 - sudo add-apt-repository ppa:team-gcc-arm-embedded/ppa -y
 - sudo apt-get update
 - sudo apt-get install gcc-arm-embedded -y

install:
 - pushd asp-1.9.2-utf8/cfg/cfg
 - wget http://toppers.jp/download.cgi/cfg-linux-static-1_9_5.gz
 - tar zxvf cfg-linux-static-1_9_5.gz
 - pwd
 - ls -l
# - $(CURDIR)/cfg -v
 - popd
 - pushd examples/multitask_arduino
 - ls -l ../../asp-1.9.2-utf8/cfg/cfg/

script:
 - make depend
 - make
