sudo: required
dist: trusty
language: cpp

compiler: gcc

before_install:
 - sudo add-apt-repository ppa:team-gcc-arm-embedded/ppa -y # -qq is for travis CI
 - sudo apt-get update
 - sudo apt-get install gcc-arm-embedded libboost1.55-all-dev -y

before_script:
 - cd asp-1.9.2-utf8/cfg/cfg
 - make
 - cd ../../../
 - cd examples/multitask_arduino

script: make depend; make
